name: React CI/CD

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ghcr.io/stillthskin/stillfrontend  # Changed to frontend

jobs:
  # -----------------------------------------------
  # 🧪 TEST JOB - React
  # -----------------------------------------------
  test:
    name: Run tests & build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --coverage --watchAll=false

      - name: Build application
        run: npm run build

      - name: Lint
        run: npm run lint || true

  # -----------------------------------------------
  # 🧱 BUILD AND PUSH DOCKER IMAGE
  # -----------------------------------------------
  build_and_push:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build React app
        run: |
          npm ci
          npm run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          build-args: |
            NODE_ENV=production

  # -----------------------------------------------
  # 🚀 DEPLOY TO SERVER
  # -----------------------------------------------
  deploy:
    name: Deploy to server via SSH
    runs-on: ubuntu-latest
    needs: build_and_push
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Deploy container
        env:
          IMAGE: ${{ env.IMAGE_NAME }}:latest
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key $DEPLOY_USER@$DEPLOY_HOST \
          "echo '$GHCR_TOKEN' | docker login ghcr.io -u '$GITHUB_ACTOR' --password-stdin && \
           docker pull $IMAGE && \
           docker stop react-app || true && \
           docker rm react-app || true && \
           docker run -d --name react-app -p 80:80 $IMAGE"
